CREATE OR REPLACE FUNCTION checkuser(un VARCHAR(30),pass VARCHAR(30))
 RETURNS Boolean
 LANGUAGE plpgsql
AS $function$
	DECLARE rs varchar(30) := '' ;
    BEGIN
    rs := (select username from users where un=username and pass=pwd);
	IF rs != '' THEN 
	RETURN TRUE;
	ELSE
	RETURN FALSE;
	END IF;
    END;
$function$;

CREATE OR REPLACE FUNCTION createlog () 
RETURNS TRIGGER AS $$
BEGIN
IF (TG_OP = 'DELETE') THEN
INSERT INTO Log SELECT 'D', now();
RETURN OLD;
ELSIF (TG_OP = 'UPDATE') THEN
INSERT INTO Log SELECT 'U', now();
RETURN NEW;
ELSIF (TG_OP = 'INSERT') THEN
INSERT INTO Log SELECT 'I', now();
RETURN NEW;
END IF;
RETURN NULL; 
END;
$$ 
LANGUAGE plpgsql;

CREATE TRIGGER keeplog
AFTER INSERT OR UPDATE OR DELETE ON Log
FOR EACH ROW EXECUTE PROCEDURE createlog();
